# Board configuration generated by CMake
# DO NOT EDIT - this file is auto-generated from board_config.rb.in

module BoardConfig
  # Board name
  BOARD_NAME = "M5Stack CoreS3 SE"

  # SD Card interface mode: "sdmmc" or "spi"
  SD_MODE = "spi"

  # SDMMC pins (for Freenove)
  SD_CLK_PIN = -1
  SD_CMD_PIN = -1
  SD_D0_PIN  = -1

  # SPI pins (for M5Stack)
  SD_SCK_PIN  = 36
  SD_MISO_PIN = 35
  SD_MOSI_PIN = 37
  SD_CS_PIN   = 4

  # SPI unit for SD card (SPI mode only)
  SD_SPI_UNIT = :ESP32_SPI2_HOST
end
