# Board configuration generated by CMake
# DO NOT EDIT - this file is auto-generated from board_config.rb.in

module BoardConfig
  # Board name
  BOARD_NAME = "M5Stack Tab5 (USB-MIDI device)"

  # SD Card interface mode: "sdmmc" or "spi"
  SD_MODE = "spi"

  # SDMMC pins (for Freenove / CrowPanel)
  SD_CLK_PIN = -1
  SD_CMD_PIN = -1
  SD_D0_PIN  = -1

  # SDMMC host slot the card slot is wired to (-1 = let the driver pick).
  # Not implied by the pins: on the ESP32-P4 slot 0 has dedicated IOMUX pins
  # that the GPIO matrix cannot reach, so a card on those pins is only
  # reachable through slot 0.
  SD_SLOT = -1

  # SDMMC bus clock ceiling in kHz (-1 = driver default, 20MHz)
  SD_FREQ_KHZ = -1

  # SPI pins (for M5Stack)
  SD_SCK_PIN  = 43
  SD_MISO_PIN = 39
  SD_MOSI_PIN = 44
  SD_CS_PIN   = 42

  # SPI unit for SD card (SPI mode only)
  SD_SPI_UNIT = :ESP32_SPI2_HOST

  # MIDI Device Configuration
  # SAM2695 synthesizer pins
  SAM2695_TX_PIN = 53
  SAM2695_RX_PIN = 54
  HAS_SAM2695 = true

  # USB-MIDI Host support
  HAS_USB_MIDI_HOST = true

  # USB-MIDI Device support (for future implementation)
  HAS_USB_MIDI_DEVICE = true

  # Primary I2C bus for accessories (e.g. DFRobot rotary encoders). Shares
  # pins with the SAM2695 UART header (Port A on Tab5) on every board that has
  # one, so HAS_PRIMARY_I2C and HAS_SAM2695 are mutually exclusive at runtime,
  # not at build time -- pick one use per script. PRIMARY_I2C_UNIT names the
  # underlying hardware bus, which varies by board (e.g. CrowPanel's touch
  # controller already owns I2C0, so its accessory bus is I2C1).
  HAS_PRIMARY_I2C      = true
  PRIMARY_I2C_SDA_PIN  = 53
  PRIMARY_I2C_SCL_PIN  = 54
  PRIMARY_I2C_UNIT     = "ESP32_I2C0"
end
