# Board configuration generated by CMake
# DO NOT EDIT - this file is auto-generated from board_config.rb.in

module BoardConfig
  # Board name
  BOARD_NAME = "Freenove ESP32-S3"

  # SD Card interface mode: "sdmmc" or "spi"
  SD_MODE = "sdmmc"

  # SDMMC pins (for Freenove)
  SD_CLK_PIN = 39
  SD_CMD_PIN = 38
  SD_D0_PIN  = 40

  # SPI pins (for M5Stack)
  SD_SCK_PIN  = -1
  SD_MISO_PIN = -1
  SD_MOSI_PIN = -1
  SD_CS_PIN   = -1

  # SPI unit for SD card (SPI mode only)
  SD_SPI_UNIT = :ESP32_SPI2_HOST
end
