# Board configuration generated by CMake
# DO NOT EDIT - this file is auto-generated from board_config.rb.in

module BoardConfig
  # Board name
  BOARD_NAME = "Freenove ESP32-S3"

  # SD Card interface mode: "sdmmc" or "spi"
  SD_MODE = "sdmmc"

  # SDMMC pins (for Freenove)
  SD_CLK_PIN = 39
  SD_CMD_PIN = 38
  SD_D0_PIN  = 40

  # SPI pins (for M5Stack)
  SD_SCK_PIN  = -1
  SD_MISO_PIN = -1
  SD_MOSI_PIN = -1
  SD_CS_PIN   = -1

  # SPI unit for SD card (SPI mode only)
  SD_SPI_UNIT = :ESP32_SPI2_HOST
end

require 'machine'
require "watchdog"
Watchdog.disable
require "shell"
# BoardConfig is defined above (concatenated by CMake)
STDIN = IO.new
STDOUT = IO.new

puts "Board: #{BoardConfig::BOARD_NAME}"

# Scan SD card for Ruby scripts and notify C side
def notify_scripts_to_c
  begin
    sm = ScriptManager.new
    sm.clear
    Dir.open("/sd") do |dir|
      while entry = dir.read
        next if entry == "." || entry == ".."
        next unless entry.end_with?(".rb")
        sm.add(entry)
      end
    end
    sm.set_ready
    puts "Scripts notified to C side"
  rescue => e
    puts "Failed to notify scripts: #{e.message}"
  end
end

# Setup flash disk
begin
  STDIN.echo = false
  puts "Initializing FLASH disk as the root volume... "
  Shell.setup_root_volume(:flash, label: 'storage')
  Shell.setup_system_files
  puts "Available"
rescue => e
  puts "Not available"
  puts "#{e.message} (#{e.class})"
end

# Setup SD card
if BoardConfig::SD_MODE == "none"
  puts "SD card disabled (GPIO conflict with PSRAM)"
else
  begin
    puts "Initializing SD card (#{BoardConfig::SD_MODE} mode)..."
    if BoardConfig::SD_MODE == "sdmmc"
      # SDMMC mode
      require "sdmmc"
      puts "  CLK=#{BoardConfig::SD_CLK_PIN}, CMD=#{BoardConfig::SD_CMD_PIN}, D0=#{BoardConfig::SD_D0_PIN}"
      sdmmc = SDMMC.new(
        clk_pin: BoardConfig::SD_CLK_PIN,
        cmd_pin: BoardConfig::SD_CMD_PIN,
        d0_pin:  BoardConfig::SD_D0_PIN
      )
      Shell.setup_sdcard(sdmmc)
    else
      # SPI mode (M5Stack)
      require "spi"
      puts "  SCK=#{BoardConfig::SD_SCK_PIN}, MISO=#{BoardConfig::SD_MISO_PIN}, MOSI=#{BoardConfig::SD_MOSI_PIN}, CS=#{BoardConfig::SD_CS_PIN}"
      spi = SPI.new(
        frequency: 5_000_000,
        unit: BoardConfig::SD_SPI_UNIT,
        sck_pin:  BoardConfig::SD_SCK_PIN,
        cipo_pin: BoardConfig::SD_MISO_PIN,
        copi_pin: BoardConfig::SD_MOSI_PIN,
        cs_pin:   BoardConfig::SD_CS_PIN
      )
      Shell.setup_sdcard(spi)
    end

    # Notify C side about available Ruby scripts
    notify_scripts_to_c
  rescue => e
    puts "SD card not available: #{e.message}"
  end
end

GC.start

# Perform MIDI cleanup (All Notes Off, MIDI Stop)
def perform_midi_cleanup
  begin
    sm = ScriptManager.new
    sm.cleanup_midi
    puts "MIDI cleanup done"
  rescue => e
    # cleanup_midi may not be available in all environments
    puts "MIDI cleanup skipped: #{e.message}"
  end
end

# Execute autorun script (called once at startup)
def run_autorun_script(script_path)
  puts "Autorun: #{script_path}"
  begin
    unless File.exist?(script_path)
      puts "Script not found: #{script_path}"
      return
    end

    # Execute the script
    load script_path
    puts "Script finished: #{script_path}"
  rescue => e
    puts "Script error: #{e.message}"
  ensure
    # Always perform MIDI cleanup
    perform_midi_cleanup
    GC.start
  end
end

# Request script load (saves to NVS and restarts ESP32)
def request_load_script(script_path)
  sm = ScriptManager.new
  puts "Scheduling: #{script_path}"
  puts "Restarting ESP32..."
  sleep_ms 100
  if sm.set_autorun(script_path)
    sm.esp_restart
    # Never returns
  else
    puts "Failed to set autorun"
  end
end

puts "Initialization complete."

# Check for autorun script at startup
sm = ScriptManager.new
autorun_script = sm.get_autorun
if autorun_script
  # Clear autorun first (so we don't loop on crash)
  sm.clear_autorun
  puts "Found autorun script: #{autorun_script}"
  run_autorun_script(autorun_script)
end

puts "Available commands:"
puts "  load /sd/app.rb  - Load and run a script (restarts ESP32)"
puts "  heap             - Show free heap memory"
puts "  restart          - Restart ESP32"
print "> "

# Main loop - only handles console input and UI requests
loop do
  # Check for console input (load command)
  # Note: check_console now handles set_autorun + esp_restart internally
  console_script = sm.check_console
  if console_script
    # Console returned a script path - request load (will restart)
    request_load_script(console_script)
  end

  # Check for script request from UI
  script_path = sm.get_requested
  if script_path
    sm.clear_request
    # UI requested a script - request load (will restart)
    request_load_script(script_path)
  end

  sleep_ms 100
end
