# Board configuration generated by CMake
# DO NOT EDIT - this file is auto-generated from board_config.rb.in

module BoardConfig
  # Board name
  BOARD_NAME = "Freenove ESP32-S3"

  # SD Card interface mode: "sdmmc" or "spi"
  SD_MODE = "sdmmc"

  # SDMMC pins (for Freenove)
  SD_CLK_PIN = 39
  SD_CMD_PIN = 38
  SD_D0_PIN  = 40

  # SPI pins (for M5Stack)
  SD_SCK_PIN  = -1
  SD_MISO_PIN = -1
  SD_MOSI_PIN = -1
  SD_CS_PIN   = -1

  # SPI unit for SD card (SPI mode only)
  SD_SPI_UNIT = :ESP32_SPI2_HOST
end

require 'machine'
require "watchdog"
Watchdog.disable
require "shell"
# BoardConfig is defined above (concatenated by CMake)
STDIN = IO.new
STDOUT = IO.new

puts "Board: #{BoardConfig::BOARD_NAME}"

# Scan SD card for Ruby scripts and notify C side
def notify_scripts_to_c
  begin
    sm = ScriptManager.new
    sm.clear
    Dir.open("/sd") do |dir|
      while entry = dir.read
        next if entry == "." || entry == ".."
        next unless entry.end_with?(".rb")
        sm.add(entry)
      end
    end
    sm.set_ready
    puts "Scripts notified to C side"
  rescue => e
    puts "Failed to notify scripts: #{e.message}"
  end
end

# Setup flash disk
begin
  STDIN.echo = false
  puts "Initializing FLASH disk as the root volume... "
  Shell.setup_root_volume(:flash, label: 'storage')
  Shell.setup_system_files
  puts "Available"
rescue => e
  puts "Not available"
  puts "#{e.message} (#{e.class})"
end

# Setup SD card
if BoardConfig::SD_MODE == "none"
  puts "SD card disabled (GPIO conflict with PSRAM)"
else
  begin
    puts "Initializing SD card (#{BoardConfig::SD_MODE} mode)..."
    if BoardConfig::SD_MODE == "sdmmc"
      # SDMMC mode
      require "sdmmc"
      puts "  CLK=#{BoardConfig::SD_CLK_PIN}, CMD=#{BoardConfig::SD_CMD_PIN}, D0=#{BoardConfig::SD_D0_PIN}"
      sdmmc = SDMMC.new(
        clk_pin: BoardConfig::SD_CLK_PIN,
        cmd_pin: BoardConfig::SD_CMD_PIN,
        d0_pin:  BoardConfig::SD_D0_PIN
      )
      Shell.setup_sdcard(sdmmc)
    else
      # SPI mode (M5Stack)
      require "spi"
      puts "  SCK=#{BoardConfig::SD_SCK_PIN}, MISO=#{BoardConfig::SD_MISO_PIN}, MOSI=#{BoardConfig::SD_MOSI_PIN}, CS=#{BoardConfig::SD_CS_PIN}"
      spi = SPI.new(
        frequency: 5_000_000,
        unit: BoardConfig::SD_SPI_UNIT,
        sck_pin:  BoardConfig::SD_SCK_PIN,
        cipo_pin: BoardConfig::SD_MISO_PIN,
        copi_pin: BoardConfig::SD_MOSI_PIN,
        cs_pin:   BoardConfig::SD_CS_PIN
      )
      Shell.setup_sdcard(spi)
    end

    # Notify C side about available Ruby scripts
    notify_scripts_to_c
  rescue => e
    puts "SD card not available: #{e.message}"
  end
end

GC.start

begin
  if File.exist?("/home/app.mrb")
    puts "Loading app.mrb"
    load "/home/app.mrb"
  elsif File.exist?("/home/app.rb")
    puts "Loading app.rb"
    load "/home/app.rb"
  elsif File.exist?("/sd/app.rb")
    puts "  Loading /sd/app.rb..."
    load "/sd/app.rb"
  end

  GC.start

  # $shell = Shell.new(clean: true)
  # puts "Starting shell...\n\n"

  # $shell.show_logo
  # $shell.start
rescue Exception => e
  puts "#{e.message} (#{e.class})"
end
